"""TK-09 — TTFB latency guard (Q10 / R2).

Invariants:
  * guard budget = legacy TTFB baseline (p90) + Δ (relative form)
  * simulated timeout → degrade to legacy path, trace marks ttfb_degrade
  * baseline file (generated by scripts/measure_legacy_ttfb.py) is consumed
    when present; falls back to a default otherwise so the guard stays armed
"""
import asyncio
import os
import sys
import tempfile
import time
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
os.environ.setdefault("TECH_DB_INDEX_DIR", tempfile.mkdtemp(prefix="tk09-"))

import ttfb_guard

PASS, FAIL = 0, 0


def check(name, fn):
    global PASS, FAIL
    try:
        fn(); print(f"  ✅ {name}"); PASS += 1
    except Exception:
        print(f"  ❌ {name}"); traceback.print_exc(); FAIL += 1


def t_budget_math(monkey_dir=None):
    """budget = baseline + Δ (relative form, not absolute).

    Phase09 runtime-budget repair: a fixture is consumed only when it is
    fresh AND describes the deployed model; the test writes its own fresh,
    model-matching fixture so this invariant stays deterministic regardless
    of the committed fixture's age.
    """
    import json as _json
    from datetime import datetime, timedelta, timezone
    fixture_dir = Path(monkey_dir or tempfile.mkdtemp(prefix="tk09-fresh-"))
    fixture = fixture_dir / "baseline_legacy.json"
    generated = datetime.now(timezone.utc) - timedelta(hours=1)
    fixture.write_text(_json.dumps({
        "p90_ms": 1000, "mean_ms": 900, "model": "glm-5.3-flash",
        "method": "rewrite(history=[])+hybrid_search",
        "generated_at": generated.isoformat(),
    }), encoding="utf-8")
    real_path = ttfb_guard.BASELINE_PATH
    real_model = os.environ.get("ZAI_MODEL")
    os.environ["ZAI_MODEL"] = "glm-5.3-flash"
    ttfb_guard.BASELINE_PATH = fixture
    try:
        snap = ttfb_guard.snapshot()
        assert snap["baseline_source"] == "file"  # fresh + model-matching
        assert snap["baseline_ms"] == 1000
        assert snap["guard_ms"] == snap["baseline_ms"] + snap["delta_ms"]
        assert ttfb_guard.guard_budget_s() == snap["guard_ms"] / 1000.0
    finally:
        ttfb_guard.BASELINE_PATH = real_path
        if real_model is None:
            os.environ.pop("ZAI_MODEL", None)
        else:
            os.environ["ZAI_MODEL"] = real_model


def t_stale_baseline_rejected(monkey_dir=None):
    """Phase09 repair RC2: a stale baseline must NOT arm the guard with
    stale numbers — the conservative default is used instead.  The recorded
    model matches the effective model so the STALENESS dimension is
    isolated (model identity is covered by the repair suite's F3 checks)."""
    import json as _json
    from datetime import datetime, timedelta, timezone
    fixture_dir = Path(monkey_dir or tempfile.mkdtemp(prefix="tk09-stale-"))
    fixture = fixture_dir / "baseline_legacy.json"
    generated = datetime.now(timezone.utc) - timedelta(hours=4000)
    fixture.write_text(_json.dumps({
        "p90_ms": 1, "mean_ms": 1,
        "model": ttfb_guard._current_model() or "glm-5.3-flash",
        "generated_at": generated.isoformat(),
    }), encoding="utf-8")
    real_path = ttfb_guard.BASELINE_PATH
    ttfb_guard.BASELINE_PATH = fixture
    try:
        snap = ttfb_guard.snapshot()
        assert snap["baseline_source"] == "default_stale"
        assert snap["baseline_ms"] == ttfb_guard.DEFAULT_BASELINE_MS
        # the guard stays armed: default, never the stale 1ms value
        assert ttfb_guard.load_baseline_ms() == ttfb_guard.DEFAULT_BASELINE_MS
    finally:
        ttfb_guard.BASELINE_PATH = real_path


def t_default_when_missing(monkey_dir=None):
    """Missing baseline file → default keeps the guard armed."""
    real = ttfb_guard.BASELINE_PATH
    ttfb_guard.BASELINE_PATH = Path(monkey_dir or tempfile.mkdtemp()) / "nope.json"
    try:
        assert ttfb_guard.load_baseline_ms() == ttfb_guard.DEFAULT_BASELINE_MS
        assert ttfb_guard.snapshot()["baseline_source"] == "default_missing"
    finally:
        ttfb_guard.BASELINE_PATH = real


async def _simulate_timeout():
    """Server-equivalent wiring: wait_for(timeout=budget) over a slow loop."""
    budget_s = ttfb_guard.guard_budget_s()
    trace_stages = []

    async def slow_agentic():
        await asyncio.sleep(budget_s + 5)      # would exceed the guard
        return "state"

    try:
        await asyncio.wait_for(slow_agentic(), timeout=budget_s)
        return None, trace_stages
    except asyncio.TimeoutError:
        trace_stages.append({"stage": "ttfb_degrade",
                             "budget_ms": ttfb_guard.snapshot()["guard_ms"],
                             "action": "degrade_to_legacy"})
        return "legacy_fallback", trace_stages


def t_timeout_degrades():
    result, stages = asyncio.run(_simulate_timeout())
    assert result == "legacy_fallback"
    assert stages[-1]["stage"] == "ttfb_degrade"
    assert stages[-1]["action"] == "degrade_to_legacy"


def t_fast_path_untouched():
    """Loop under budget completes normally (no degrade)."""
    async def go():
        budget_s = ttfb_guard.guard_budget_s()
        async def fast():
            await asyncio.sleep(0.01)
            return "state"
        return await asyncio.wait_for(fast(), timeout=budget_s)
    assert asyncio.run(go()) == "state"


def t_env_override():
    """QA_TTFB_DELTA_MS tunes Δ without touching the baseline."""
    real = os.environ.get("QA_TTFB_DELTA_MS")
    try:
        os.environ["QA_TTFB_DELTA_MS"] = "1"
        snap = ttfb_guard.snapshot()
        assert snap["delta_ms"] == 1 and snap["guard_ms"] == snap["baseline_ms"] + 1
    finally:
        if real is None:
            os.environ.pop("QA_TTFB_DELTA_MS", None)
        else:
            os.environ["QA_TTFB_DELTA_MS"] = real


if __name__ == "__main__":
    print("TK-09 — TTFB latency guard")
    for name, fn in [
        ("budget = legacy baseline + Δ (fresh file consumed)", t_budget_math),
        ("stale baseline rejected → conservative default", t_stale_baseline_rejected),
        ("missing baseline → default keeps guard armed", t_default_when_missing),
        ("simulated timeout → legacy degrade + trace", t_timeout_degrades),
        ("fast loop unaffected", t_fast_path_untouched),
        ("Δ overridable via env", t_env_override),
    ]:
        print(f"── {name}")
        check(name, fn)
    print("=" * 62)
    print(f"  TK-09 Results: {PASS} passed, {FAIL} failed")
    print("=" * 62)
    sys.exit(1 if FAIL else 0)
