"""
TK-09 — TTFB latency guard (Q10 / R2).

Budget definition (spec):
  TTFB口径 = 流式首字节前的后端开销 (rewrite + retrieval + agentic control),
  NOT including LLM streaming generation time.
  Expression form: new-path ≤ legacy-TTFB-baseline + Δ  (relative, so the
  budget is not blown by legacy's own drift).

Enforcement:
  run_agentic_loop is wrapped in asyncio.wait_for(timeout=TTFB_GUARD_S).
  On timeout → trace stage "ttfb_degrade" → the query falls back to the
  legacy single-pass path (answer still returns).

The baseline file (test_fixtures/ttfb/baseline_legacy.json) is generated by
scripts/measure_legacy_ttfb.py for nightly replay; a missing file falls back
to DEFAULT_BASELINE_MS so the guard is always armed.
"""
import json
import os
from pathlib import Path

_HERE = Path(__file__).resolve().parent

# Δ: extra backend headroom the agentic path gets over legacy (ms).
_DEFAULT_DELTA_MS = 2000


def _delta_ms() -> int:
    """Δ read per-call so env changes apply without re-import."""
    return int(os.environ.get("QA_TTFB_DELTA_MS", str(_DEFAULT_DELTA_MS)))
# Fallback baseline when no measurement exists yet (ms).
DEFAULT_BASELINE_MS = int(os.environ.get("QA_TTFB_BASELINE_MS", "4000"))
BASELINE_PATH = _HERE / "test_fixtures" / "ttfb" / "baseline_legacy.json"


def load_baseline_ms() -> int:
    """Legacy TTFB baseline in ms (p90), or DEFAULT_BASELINE_MS."""
    try:
        data = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
        ms = data.get("p90_ms") or data.get("mean_ms")
        if ms and int(ms) > 0:
            return int(ms)
    except (OSError, ValueError, TypeError):
        pass
    return DEFAULT_BASELINE_MS


def guard_budget_ms() -> int:
    """Total TTFB guard budget: legacy baseline + Δ."""
    return load_baseline_ms() + _delta_ms()


def guard_budget_s() -> float:
    return guard_budget_ms() / 1000.0


def snapshot() -> dict:
    """For trace reporting."""
    return {
        "baseline_ms": load_baseline_ms(),
        "delta_ms": _delta_ms(),
        "guard_ms": guard_budget_ms(),
        "baseline_source": "file" if BASELINE_PATH.exists() else "default",
    }
