"""TK-09 — TTFB latency guard (Q10 / R2), Phase09 runtime-budget repair.

Budget definition (spec):
TTFB口径 = pre-first-answer-byte backend overhead (rewrite + retrieval +
agentic control), NOT including LLM streaming generation time.

Expression form: guard = legacy-TTFB-baseline + Δ (relative), THEN capped by
the FAST total-deadline collision bound:

    guard <= FAST_total - (2 * verifier_window + post_generation_slack)
                          - min_generation_window

The cap can only TIGHTEN the guard: the pre-answer phase must never be able
to consume the downstream correctness reserve (claim mapping + final
verifier) plus the minimum generation window.  Per final_spec.md §16/§28 and
decision-register Q293/Q294, all numeric values are versioned profile
configuration derived from benchmarks, never canonical behavioral truth.

Baseline policy (Phase09 repair RC2): the baseline fixture must describe the
deployed model and be fresh.  A baseline measured against a different model
(or stale beyond QA_TTFB_BASELINE_MAX_AGE_H, default 336h) is REJECTED and
the conservative env default (QA_TTFB_BASELINE_MS, 4000ms) is used instead.
This prevents a silently stale/foreign baseline from arming a guard that
systematically degrades normal production traffic to the legacy path.

Enforcement:
run_agentic_loop wrapped in asyncio.wait_for(timeout=TTFB_GUARD_S).
On timeout → trace stage "ttfb_degrade" → falls back
legacy single-pass path (answer still returns; correctness post-stages
remain enforced).

baseline file (test_fixtures/ttfb/baseline_legacy.json) is generated by
scripts/measure_legacy_ttfb.py; missing/invalid/stale/foreign-model files
fall back to DEFAULT_BASELINE_MS so the guard always stays armed.
"""
import json
import os
import time
from pathlib import Path

_HERE = Path(__file__).resolve().parent

# Δ: backend headroom the agentic path gets over legacy (ms).
_DEFAULT_DELTA_MS = 2000


def _delta_ms() -> int:
    """Δ; per-call so env changes apply without re-import."""
    return int(os.environ.get("QA_TTFB_DELTA_MS", str(_DEFAULT_DELTA_MS)))


# Fallback baseline when no valid measurement exists (ms).
DEFAULT_BASELINE_MS = int(os.environ.get("QA_TTFB_BASELINE_MS", "4000"))

# Baseline freshness bound (hours). A measurement older than this is stale.
DEFAULT_BASELINE_MAX_AGE_H = float(
    os.environ.get("QA_TTFB_BASELINE_MAX_AGE_H", "336"))

# The model identity a baseline must have been measured with.  When
# ZAI_MODEL is unset (unit tests / model-agnostic deployments) the model
# check is skipped and any recorded model is accepted.
BASELINE_PATH = _HERE / "test_fixtures" / "ttfb" / "baseline_legacy.json"


def _current_model() -> str:
    return (os.environ.get("ZAI_MODEL") or "").strip()


def _validate_baseline(data) -> tuple:
    """Validate a parsed baseline fixture.

    Returns (model_ok, source_tag, age_hours).  source_tag is a diagnostic
    for the snapshot; the caller decides which fallback to use.
    """
    if not isinstance(data, dict):
        return False, "default_error", float("inf")
    ms = data.get("p90_ms", data.get("mean_ms"))
    try:
        ms = int(ms)
    except (TypeError, ValueError):
        return False, "default_error", float("inf")
    if ms <= 0:
        return False, "default_error", float("inf")
    recorded_model = str(data.get("model", "")).strip()
    current = _current_model()
    model_ok = (not current) or (recorded_model == current)
    generated_at = str(data.get("generated_at", ""))
    age_h = _baseline_age_hours(generated_at)
    fresh = age_h <= DEFAULT_BASELINE_MAX_AGE_H
    if not model_ok:
        return False, "default_no_model", age_h
    if not fresh:
        return False, "default_stale", age_h
    return True, "file", age_h


def _baseline_age_hours(generated_at: str) -> float:
    """Age of a baseline timestamp in hours; inf when unparseable."""
    if not generated_at:
        return float("inf")
    try:
        from datetime import datetime
        txt = generated_at.strip().replace("Z", "+00:00")
        ts = datetime.fromisoformat(txt)
        if ts.tzinfo is None:
            ts = ts.astimezone()
        return max(0.0, (datetime.now(ts.tzinfo) - ts).total_seconds() / 3600.0)
    except (ValueError, TypeError, OverflowError):
        return float("inf")


def load_baseline_ms() -> int:
    """Legacy TTFB baseline (ms, p90 preferred) or DEFAULT_BASELINE_MS."""
    try:
        data = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError):
        return DEFAULT_BASELINE_MS
    model_ok, _source, _age = _validate_baseline(data)
    if not model_ok:
        return DEFAULT_BASELINE_MS
    ms = data.get("p90_ms", data.get("mean_ms"))
    try:
        ms = int(ms)
    except (TypeError, ValueError):
        return DEFAULT_BASELINE_MS
    return ms if ms > 0 else DEFAULT_BASELINE_MS


def _deadline_budget_ms() -> tuple:
    """(fast_total_ms, downstream_reserve_ms, guard_cap_ms).

    The guard may never grow so large that a full-length pre-answer phase
    collides with the correctness-critical post-generation reserve
    (claim mapping + final verifier + slack) plus the minimum safe
    generation window.  Values mirror server.py's env knobs so the runtime
    and any external qualification harness compute the SAME numbers.
    """
    fast_total_s = float(os.environ.get("QA_RUNTIME_FAST_DEADLINE", "60"))
    verifier_s = float(os.environ.get("QA_RUNTIME_VERIFIER_S", "10"))
    slack_s = float(os.environ.get("QA_POST_GENERATION_SLACK_S", "2"))
    min_gen_s = float(os.environ.get("QA_MIN_GENERATION_WINDOW_S", "8"))
    total_ms = fast_total_s * 1000.0
    reserve_ms = (2.0 * verifier_s + slack_s) * 1000.0
    cap_ms = max(0.0, total_ms - reserve_ms - min_gen_s * 1000.0)
    return total_ms, reserve_ms, cap_ms


def guard_budget_ms() -> int:
    """Baseline + Δ, then a conservative FAST total-deadline cap.

    The cap reserves two verifier windows (claim mapping and final
    verification), post-generation slack, and a minimum generation window.
    It can only TIGHTEN the guard; it never changes the FAST total default.
    """
    return min(load_baseline_ms() + _delta_ms(), int(_deadline_budget_ms()[2]))


def guard_budget_s() -> float:
    return guard_budget_ms() / 1000.0


def snapshot() -> dict:
    """For trace reporting (all values externally qualifiable — R5)."""
    try:
        data = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
        model_ok, source, age_h = _validate_baseline(data)
    except FileNotFoundError:
        source, model_ok, age_h = "default_missing", False, float("inf")
    except (OSError, ValueError, TypeError):
        source, model_ok, age_h = "default_error", False, float("inf")
    total_budget_ms, reserve_ms, cap_ms = _deadline_budget_ms()
    return {
        "baseline_ms": load_baseline_ms(),
        "delta_ms": _delta_ms(),
        "guard_ms": guard_budget_ms(),
        "baseline_source": source,
        "total_budget_ms": total_budget_ms,
        "reserve_ms": reserve_ms,
        "cap_ms": cap_ms,
        "guard_capped": (load_baseline_ms() + _delta_ms()) > cap_ms,
        "baseline_model_ok": model_ok,
        "baseline_age_h": (age_h if age_h != float("inf") else -1.0),
    }
